package com.cinebook.enums;

public enum SchedulingConflictType {
    SHOWTIME_OVERLAP,
    TURNAROUND_VIOLATION,
    OUTSIDE_OPERATING_HOURS,
    AUDITORIUM_INACTIVE,
    AUDITORIUM_MAINTENANCE,
    AUDITORIUM_DECOMMISSIONED,
    CINEMA_INACTIVE,
    MOVIE_NOT_AVAILABLE,
    INVALID_TIME,
    ALREADY_EXISTS
}